name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Instalar Gradle 7.3.3
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '7.3.3'

      - name: Compilar
        run: gradle build --stacktrace

      - name: Publicar JAR como artifact
        uses: actions/upload-artifact@v4
        with:
          name: superfurnace
          path: build/libs/*.jar
          if-no-files-found: error
